### ISSUE TITLE
[Bug] Generate a model is very slow, occasionaly leading to `FatalError`

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/devtools-issues#26] opened 2021-12-03 12:51 UTC
# Bug report

### What I did

Generate a model

### What I expected to happen

Success, or at least no loss of data. I have to fill in the form again. 
### What happened
```
Symfony\Component\ErrorHandler\Error\FatalError
Maximum execution time of 60 seconds exceeded
http://127.0.0.1:8000/admin/devtools/model
```

### What I've already tried to fix it

Run it again. It took about 20 seconds. I only experience long times like this when I do operations like `composer update`.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.0.2 (cli) (built: Feb  3 2021 18:36:40) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.74.0@004ea195012d5132eca07a176a6e587c6a74815e

### BACKPACK VERSION:
4.1.61@4400187391eb5b73672c2b166a990cd737277409

### Operating System and Server Setup

I encountered the problem above on my [Windows 10] machine, and my web server is set up using [php artisan serve].

**Comment by tabacitu** [comment] 2021-12-03 13:48
@Polfo  - Performance depends A LOT on the web server used and the machine you're working on. **What did you input for that particular model?** With what I've tried it seems to work. 

----

@promatik this is where your feature of copy-pasting the form data (or logging the form data) would have been super-helpful to debug. Otherwise... with the info we have now, we have no way to reproduce.

**Comment by Polfo** [comment] 2021-12-03 20:34
> @Polfo - Performance depends A LOT on the web server used and the machine you're working on. **What did you input for that particular model?** With what I've tried it seems to work.

@tabacitu 
The timeout even occurs with a nearly empty model. 
Maybe it is linked to the following routine, `composer dump-autoload` is slow on my machine if composer has not run for a while.

    \vendor\backpack\devtools\src\Generators\BlueprintGenerator.php:754
    private function composerDumpAutoload()
    {
        if (! app()->runningUnitTests()) {
            exec('composer dump-autoload');
            sleep(2);
        }
    }

**Comment by Polfo** [comment] 2021-12-03 20:51
The `sleep(2);` looks strange to me. Is this a reliable way to do what is intended?

**Comment by tabacitu** [comment] 2021-12-04 06:36
> The sleep(2); looks strange to me. Is this a reliable way to do what is intended?

No, it is not 😀 It is exactly for this use cases - computers where `dump-autoload` takes a long time... We did not expect it to take longer than 2sec on any machine... That might be the source of our problems...

**Comment by Polfo** [comment] 2021-12-04 08:40
Well, lucky you to have that performance. 
To be sure, it is not only on my personal PC, I tested on one of my webserver, `time composer dump-autoload` takes 16 seconds.
```
Generated optimized autoload files containing 5902 classes
real    0m16.341s
user    0m2.310s
sys     0m1.566s

```

On an other webserver, it took 6 seconds.
```
xx@ssh01.cluster006.gra.hosting.ovh.net (php/7.4/production/stable64) telraam $ time composer dump-autoload
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Package manifest generated successfully.
Generated optimized autoload files containing 2845 classes

real    0m6,284s
user    0m1,112s
sys     0m0,414s

```

**Comment by Polfo** [comment] 2021-12-04 08:46
I still don't understand the `sleep()`. Isn't `exec()` waiting for the external program to be finished? How would it be able to return  the output without doing that?

**Comment by promatik** [comment] 2021-12-05 02:49
@Polfo the `sleep` was a weird trade off we came up to, indeed – weird. But actually it has few to do with your issue.

The `composer dump-autoload` runs, DevTools waits for it to finish, but if DevTools reloads after that – **instantly** – it breaks, because apparently it needs some milliseconds for the `dump-autoload` to be ready(?), that's why we added the 2 seconds.

I think in this case there is not much we (DevTools) can do. The `Maximum execution time of 60 seconds exceeded` is a PHP setting, DevTools has no way to know how long the `composer dump-autoload` takes to run.

This same thing may happen with Backpack/BackupManager, it also takes a lot of time to generate the backup, if it times out, actually there is nothing BackupManager can do about it, it's up to the developer to raise the "Maximum execution time" PHP setting.

What I suggest, is to add a note on the Installation.
@Polfo, @tabacitu please let me know if I'm wrong ✌

**Comment by Polfo** [comment] 2021-12-05 14:23
I agree that if you need to run `composer dump-autoload`, there is nothing you can do about the timeout issue. I did not expected this to be necessary.

**Comment by tabacitu** [comment] 2021-12-07 03:58
> Well, lucky you to have that performance.

Yes, I can't stand waiting 😅  But I have an 8GB M1 Macbook Air - it's fast, but it's an ultrabook... not a rocketship by any means. And when I run `time composer dump-autoload` I'm getting:

```
composer dump-autoload  0.36s user 0.17s system 65% cpu 0.801 total
```

That's actually an interesting thing to find out... an average duration of `dump-autoload`...

----

@Polfo are you sure this is not project-specific? I've been using Composer for 7-8 years now, and it's never happened to me for a `composer dump-autoload` to take 16s - it sounds like a _very_ long time. Is it possible that in your `composer.json` you have a lot of scripts in your `post-autoload-dump` hook? AFAIK the default one looks like this:

```json
"scripts": {
// ..
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ],
//..
}
```

**Comment by Polfo** [comment] 2021-12-13 11:08
I agree there must be something slowing down my machine, but I can't pin it down. It is not the scripts since the performance is the same when running `time composer dump-autoload --no-scripts`

**Comment by tabacitu** [comment] 2022-02-15 09:21
I'm going to close this, since it seems like it's machine-specific. If anybody else gets performance issues, please reply here with your machine & setup, maybe it'll provide more insight and we can reopen.

Cheers!

**Closed by tabacitu** 2022-02-15 09:21 UTC
