### ISSUE TITLE
[Bug] During inheritance of JsonSerializable: Uncaught ErrorException: Return type of Backpack\DevTools\CustomFile::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed

### ISSUE THREAD

**Issue by dandarie** [Laravel-Backpack/devtools-issues#69] opened 2023-11-05 12:54 UTC
# Bug report

### What I did

I installed Laravel 10, Backpack Crud, Pro and DevTools.

### What I expected to happen

I expected DevTools to work.

### What happened

This FatalError is raised when I try to access Devtools.

### What I've already tried to fix it

Used #[\ReturnTypeWillChange], temporarily, in \Backpack\DevTools\CustomFile::jsonSerialize()

```
#[\ReturnTypeWillChange]
public function jsonSerialize()
{
    return $this->toArray();
}
```

Also, changing the return type to array solves the problem:

```
public function jsonSerialize(): array
{
    return $this->toArray();
}
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.12 (cli) (built: Oct 26 2023 17:33:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.12, Copyright (c), by Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

### LARAVEL VERSION:
10.30.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.1
backpack/crud: 6.3.0
backpack/devtools: 3.0.0
backpack/generators: v4.0.2
backpack/pro: 2.0.18
backpack/theme-tabler: 1.1.1

### Operating System and Server Setup

I encountered the problem above on my Linux (Pop!_OS 22.04 LTS) machine, and my web server is set up using docker:
 - nginxproxy/nginx-proxy:latest: reverse proxy
 - nginx:latest: app web server
 - local/php-fpm:xdebug-8.2: local build of php-fpm 8.2, based on phpdockerio/php:8.2-fpm

**Comment by tabacitu** [comment] 2023-11-07 09:27
Hey @dandarie ,

Thanks for the bug report. 

<details>
  <summary>No matter how much I tried, I could not reproduce this. And I have the same versions. Click here to see:</summary>

```
### PHP VERSION:
PHP 8.2.11 (cli) (built: Sep 29 2023 00:10:16) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.11, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.30.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/activity-log: 2.0.0
backpack/backupmanager: v5.0.0
backpack/basset: 1.2.1
backpack/crud: 6.3.0
backpack/demo: dev-main
backpack/devtools: 3.0.0
backpack/editable-columns: 3.0.2
backpack/filemanager: 3.0.5
backpack/generators: v4.0.2
backpack/language-switcher: 1.0.1
backpack/logmanager: v5.0.1
backpack/medialibrary-uploaders: 1.0.1
backpack/menucrud: v4.0.1
backpack/newscrud: v5.0.0
backpack/pagemanager: 3.2.0
backpack/permissionmanager: 7.1.1
backpack/pro: 2.0.18
backpack/revise-operation: 2.0.0
backpack/settings: 3.1.0
backpack/theme-coreuiv2: 1.2.2
backpack/theme-coreuiv4: 1.1.1
backpack/theme-tabler: 1.1.1
```
</details>

<details>
  <summary>For me, DevTools still opens and works. Click here to see:</summary>

<img width="1474" alt="CleanShot 2023-11-07 at 11 09 17@2x" src="https://github.com/Laravel-Backpack/devtools-issues/assets/1032474/d63cb12b-c90c-4583-990b-15bdf56f6186">
</details>

That being said, I don't see any harm in specifying the `array` return type. So I've created a PR for this, merged it and will ask @pxpm to give his green light after-the-fact 👀🤞.

Can you please run a `composer update` to get DevTools 3.0.1 and tell me if it's fixed?

Thanks again!

**Comment by dandarie** [comment] 2023-11-07 10:17
My take on it was maybe Backpack 6 wasn't PHP 8.2 ready. I had another issue and went down to PHP 8.1 and removed DevTools for now.

However, I have PHP 8.2.12 and you have PHP 8.2.11 :)

I'll try again later this week.

**Comment by tabacitu** [comment] 2023-11-07 12:44
Thank you! For reference, BP v6 should work with PHP 8.2 no problem.

**Comment by tabacitu** [comment] 2023-11-07 12:44
Closing for now then. Let us know if it's not fixed this way and we'll reopen.

Cheers!

**Closed by tabacitu** 2023-11-07 12:44 UTC
Labels: Priority: MUST, bug, URGENT, Size: XS
