### ISSUE TITLE
[Bug] DevTools - should not let dev submit the form when two columns have the same name

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/devtools-issues#33] opened 2021-12-03 20:50 UTC
# Bug report

### What I did

Defined a new table where two fields accidentally have the same name, then hit Save and Back

### What I expected to happen

Error message

### What happened

Returned empty form, all data is lost.

### PHP VERSION:
PHP 8.0.2 (cli) (built: Feb  3 2021 18:36:40) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.74.0@004ea195012d5132eca07a176a6e587c6a74815e

### BACKPACK VERSION:
4.1.61@4400187391eb5b73672c2b166a990cd737277409

### Operating System and Server Setup

I encountered the problem above on my [Windows 10] machine, and my web server is set up using [php artisan serve].

**Comment by tabacitu** [comment] 2021-12-07 03:47
I thought there might be a problem on slow connections, but I tried it with ChromeDevTools's "Slow 3G" turned on, and I can't reproduce it that way either, the validation catches it:

![Screenshot 2021-12-07 at 05 44 26](https://user-images.githubusercontent.com/1032474/144962325-a43ed39d-2dae-42f3-8587-5d4586fef74f.png)

@Polfo I see in the original post you don't say what error message you get when doing this. Could you please reproduce and copy-paste the error message? Or better yet, maybe you can quickly create a GIF with your screen if you use [Loom](https://www.loom.com/) or anything else? That could give us some more info on what's happening on your machine.

Thanks!

**Comment by Polfo** [comment] 2021-12-07 04:27
@tabacitu 
1) In my case, it is not a slow connetion since it is localhost, it is slow processing.
2) There is no error message, it is as described in my first post above.

**Comment by pxpm** [comment] 2022-02-28 12:29
I am still unable to reproduce this. I am going to close this issue, if someone stumbles on this, please comment so we can re-open. 

I don't know what to fix here until I am able to reproduce it, or know for sure what is happening. We have validation in place for this specific scenario, so I guess that the validation triggered but some OTHER issue popped up. 

Just today I fixed one issue regarding `validation` problems when redirected back to the interface.

I am going to close this for now, if someone stumbles on this again, please comment so we can re-open.

Thanks.

**Closed by pxpm** 2022-02-28 12:29 UTC
Labels: Priority: MUST, bug
