### ISSUE TITLE
[Bug] Error when creating a belongsToMany relationship

### ISSUE THREAD

**Issue by gorthal** [Laravel-Backpack/devtools-issues#12] opened 2021-09-10 10:09 UTC
# Bug report

### What I did

I create a model "Context" with ( id, name )
I create a second model "Action" with (id , name) and I want to add this relationship : Action belongsToMany "Context"

### What I expected to happen

I nice looking page saying "alright boy, everything is ok" :D 
With a automated creation of "Action" and "ActionContext" model having (id, context_id, action_id)

### What happened

I've got this error : "ErrorException
Invalid argument supplied for foreach() (View: C:\_sources\__www\backpack\vendor\backpack\devtools\resources\views\livewire\relationship-schema\_partial_model.blade.php) "

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### LARAVEL VERSION:
v8.60.0@44f16a31a1d4ac8a51605550d7796e2273984a48

### BACKPACK VERSION:
4.1.52@239e60df0436f8a817facce20a2dffcb2b6e7250

### Operating System and Server Setup

I encountered the problem above on my [Windows 10 / Mac OS / Linux / ...] machine, and my web server is set up using [WAMP / XAMPP / Valet / Homestead / ...].

Windows with Laragon

**Comment by gorthal** [comment] 2021-09-10 10:51
Code capture 
![image](https://user-images.githubusercontent.com/201709/132842725-9adb1bc8-0eaf-4fe9-877a-45b365b036ef.png)

**Comment by promatik** [comment] 2021-09-12 18:33
Thank you for the details @gorthal 🙌.

This is a problem while retrieving the models, I couldn't replicate the issue my self.
I tried to clear all the models on my project, but this doesn't happen.

@pxpm I'm clueless, help ✌
This is strange, the error must come from `InteractsWithApplication` `getModelList()`, the error says "Invalid argument supplied for foreach()", so apparently it is not an array, but if it wasn't an array, it would trigger other errors before; "Call to a member function toArray() on string" on `$this->models->toArray()`, in many places we access this list before that foreach on `livewire` component, and gorthal code didn't complain about that before 🤔

**Comment by pxpm** [comment] 2021-10-14 11:28
Hello @gorthal 

Thanks for the report and sorry for taking such time to get back to this. 

While trying to reproduce this I found out some issues but not the one you described. 

I've submitted PR to devtools to fix those small issues. I will let you know when it's released and tagged. Please try a composer update after to see if it's fixed.

I think it's working on my side:

https://recordit.co/M5s3OvGKpC

Let me know,
Pedro

**Comment by tabacitu** [comment] 2021-11-04 07:36
Just tried this too and could not reproduce, tried with those exact models and attributes and it worked for me - here's my experience here - https://www.loom.com/share/f7095c3f0f2845cdbdba0317ce6db1df

@gorthal please let us know if this happened to you again and we'll reopen. Might have been fixed by an update like @pxpm said. If anybody else stumbles into this and has the same problem, please let us know - and the DevTools version please.

Cheers!

**Comment by malle-pietje** [comment] 2021-12-21 15:23
I probably am running into the same issue:
![image](https://user-images.githubusercontent.com/12016131/146954637-c31b5a20-731f-4e4b-aca4-4def66a4a568.png)

Simply trying to create a new Child Model with a couple of string, integer, and timestamp columns and a few indexes.

I've been messing with trying to do this through the Devtools too much now so back to doing this stuff manually I'm afraid.

**Comment by malle-pietje** [comment] 2021-12-21 15:25
Let me know if you want to see the contents from the log file.

**Comment by tabacitu** [comment] 2021-12-21 16:02
@malle-pietje thanks for letting us know. First of all, what version of backpack & devtools are you running - what's the output of `composer show | grep backpack`?

**Comment by tabacitu** [comment] 2021-12-21 16:05
> Simply trying to create a new Child Model with a couple of string, integer, and timestamp columns and a few indexes.

By "Child model" do you mean this was created in a separate tab, after clicking "Add Model" in the main form? Or is "Child" just the name of the model?

> I've been messing with trying to do this through the Devtools too much now so back to doing this stuff manually I'm afraid.

Sorry to hear that. If you're disappointed in DevTools and found it was more trouble than it was worth, then please do not hesitate to email me at hello@backpackforlaravel.com - I'll happily refund you.

**Comment by malle-pietje** [comment] 2021-12-21 16:07
No problem:
```sh
$ composer show | grep backpack
backpack/backupmanager               v3.0.3    Admin interface for managing backups in Backpack, on Laravel 5.2+
backpack/crud                        4.1.62    Quickly build an admin interfaces using Laravel, CoreUI, Bootstrap and jQuery.
backpack/devtools                    1.0.28    An admin UI for generating migrations, models and CRUDs
backpack/generators                  v3.1.11   Generate files for laravel projects
backpack/logmanager                  v4.0.5    An interface to preview, download and delete Laravel log files.
backpack/permissionmanager           6.0.10    Users and permissions management interface for Laravel 5 using Backpack CRUD.
backpack/settings                    3.0.13    Application settings interface for Laravel 5 using Backpack CRUD.
```
After this error appeared I double-checked things and it turns out the Model file and Migration file had been created in an earlier attempt where a different (SQL) error was thrown because I had selected charset and collation for a few columns.

After removing the charset and collation from the migration file everything worked fine.

It would seem that the existing files triggered the error?

**Comment by malle-pietje** [comment] 2021-12-21 16:09
@tabacitu By Child Model, I meant that I added a BelongsTo relationship using this feature:
![image](https://user-images.githubusercontent.com/12016131/146961922-deb2a675-62f8-4c47-8557-0b9bc3a14eba.png)
Not sure that is related though.

**Comment by malle-pietje** [comment] 2021-12-21 16:10
@tabacitu No refund needed, just hope you guys manage to get the Devtools in a stable state. I don't always have the time to try things out.

**Comment by pxpm** [comment] 2022-02-28 11:36
Hey @malle-pietje ! Thanks for the report. 

I've just submitted a PR to devtools that address this issue! 

Thanks and sorry for taking so much time to handle it 🙏 You should be able to get the fix later today with some other additional fixes.

Cheers

**Closed by pxpm** 2022-02-28 11:36 UTC
Labels: Priority: MUST, bug
